name: Unit Tests
on:
  # run for all pull requests
  # Run for all commits on feature branches
  push:
    paths:
    - 'src/**'
    - 'tests/**'
    - '.github/workflows/**'
  pull_request:
    paths:
    - 'src/**'
    - 'tests/**'
    - '.github/workflows/**'
jobs:  
  ###############################################################################
  # builds the automated tests with clang; runs tests and exports results
  googleTest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup CMake
      uses: lukka/get-cmake@latest

    - name: Configure CMake
      run: cmake -B build

    - name: Build Tests
      run: cmake --build build
    
    - name: Run Tests
      run: ctest --test-dir build --output-junit gtestresults.xml
    
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: build/**/*.xml
        github_token: ${{ secrets.GITHUB_TOKEN }}


